# Generated by Django 5.2 on 2025-05-04 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('id_chip', models.CharField(max_length=20, unique=True)),
                ('especie', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=10)),
                ('raza', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('historial_medico', models.TextField()),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
