# Generated by Django 5.2 on 2025-05-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_rename_gastos_solicitudviaje_presupuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='horas_extras',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
