# Generated by Django 5.2 on 2025-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('duracion_estimada', models.PositiveIntegerField(default=60, help_text='Duración en minutos')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
