# Generated by Django 5.2 on 2025-05-06 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'permissions': [('gestion_servicios', 'Puede gestionar servicios')], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_estimada',
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_corta',
            field=models.CharField(default='', max_length=200, verbose_name='Descripción Corta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(default=60, verbose_name='Duración en Minutos'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 6, 20, 18, 55, 291952, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='URL Amigable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo (Q)'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción Completa'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(default='', upload_to='servicios/', verbose_name='Imagen Representativa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Servicio'),
        ),
    ]
