# Generated by Django 5.2 on 2025-05-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_remove_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vet', 'Veterinario'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
    ]
