# Generated by Django 5.2 on 2025-05-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='facial_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
    ]
