# Generated by Django 5.2 on 2025-05-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_email_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dpi',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='DPI'),
        ),
    ]
