# Generated by Django 5.1.4 on 2025-05-08 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_dpi_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='facial_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FacialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.BinaryField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras_faciales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'fecha_registro'], name='usuarios_fa_usuario_7b64bf_idx')],
            },
        ),
    ]
