# Generated by Django 5.2 on 2025-05-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_facial_embedding_facialdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facialdata',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Dato Facial', 'verbose_name_plural': 'Datos Faciales'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='facial_data',
        ),
        migrations.AddField(
            model_name='facialdata',
            name='embedding',
            field=models.BinaryField(blank=True, null=True, verbose_name='Embedding temporal'),
        ),
        migrations.AlterField(
            model_name='facialdata',
            name='imagen',
            field=models.ImageField(upload_to='facial_data/%Y/%m/%d/', verbose_name='Imagen facial procesada'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='facial_embedding',
            field=models.BinaryField(blank=True, null=True, verbose_name='Embedding facial encriptado'),
        ),
    ]
