# Generated by Django 5.2 on 2025-05-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='proveedor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='ubicacion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='responsable',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
