# Generated by Django 5.1.4 on 2025-05-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cita_fecha_alter_cita_hora_alter_cita_mascota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='apellido_facturacion',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='departamento',
            field=models.CharField(default='', max_length=50, verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='direccion_facturacion',
            field=models.TextField(default='', verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='dpi',
            field=models.CharField(default='', max_length=13, verbose_name='DPI (13 dígitos)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='es_consumidor_final',
            field=models.BooleanField(default=False, verbose_name='Consumidor Final (C/F)'),
        ),
        migrations.AddField(
            model_name='cita',
            name='municipio',
            field=models.CharField(default='', max_length=50, verbose_name='Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='nit',
            field=models.CharField(default='', max_length=10, verbose_name='NIT (10 dígitos o CF)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre_facturacion',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
