# Generated by Django 5.1.4 on 2025-05-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_cita_apellido_facturacion_cita_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='nit',
            field=models.CharField(max_length=10, verbose_name='NIT (9 dígitos o CF)'),
        ),
    ]
